#!/bin/bash
#about_script
echo "The script can do the next: "
echo "------------------------------------------------------------"
echo "Add user : Add a new user to the system"
echo "Modif user : change the commint assigned to the user"
echo "Delete user : remove a user from the system"
echo "Change user password : change the logging password for the specified user"
echo "List users : list all users of the system"
echo "Add user to group : add an existing user to an existing group on the system"
echo "Remove user from group : remove an existing user from an existing group on the system"
echo "Add new group : creat a new group on the system"
echo "Delete group : deletes an existing group from the system"
echo "Modify group : change the name of an existing group"
echo "List group : list all existing groups on the system"
echo "Disable user : make the user unable to log in"
echo "Enabe user : re-enable the user to log in to the system"
echo "------------------------------------------------------------"
